import { useLocation, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { MapPin, CheckCircle, Calendar, User, Ticket, ArrowLeft, Download } from "lucide-react";
import jsPDF from "jspdf";

const BookingConfirmation = () => {
  const location = useLocation();
  const booking = location.state as any;

  const exportReceipt = () => {
    if (!booking) return;
    const doc = new jsPDF();

    // Header
    doc.setFillColor(34, 87, 55);
    doc.rect(0, 0, 210, 40, "F");
    doc.setTextColor(255);
    doc.setFontSize(24);
    doc.text("YatraPlanner", 14, 22);
    doc.setFontSize(10);
    doc.text("Your Indian Travel Companion", 14, 30);

    // Confirmation
    doc.setTextColor(34, 87, 55);
    doc.setFontSize(18);
    doc.text("Booking Confirmation", 14, 55);

    doc.setTextColor(60);
    doc.setFontSize(11);
    const details = [
      ["Booking ID", booking.booking_id],
      ["Type", booking.booking_type === "hotel" ? "Hotel Booking" : "Transport Booking"],
      ["Item", booking.item_name],
      ["Destination", booking.destination],
      ["Guest Name", booking.guest_name],
      ["Date", new Date(booking.booking_date).toLocaleDateString("en-IN", { dateStyle: "long" })],
      ["Status", "Confirmed"],
      ["Booked On", new Date(booking.created_at).toLocaleString("en-IN")],
    ];

    let y = 68;
    details.forEach(([label, value]) => {
      if (label === "Status") {
        doc.setTextColor(120);
        doc.text(label + ":", 14, y);
        // Green badge for status
        doc.setFillColor(34, 120, 55);
        doc.roundedRect(70, y - 4.5, 30, 7, 2, 2, "F");
        doc.setTextColor(255);
        doc.setFontSize(9);
        doc.text("CONFIRMED", 72, y);
        doc.setFontSize(11);
      } else {
        doc.setTextColor(120);
        doc.text(label + ":", 14, y);
        doc.setTextColor(40);
        doc.text(String(value), 70, y);
      }
      y += 9;
    });

    // Divider
    y += 5;
    doc.setDrawColor(34, 87, 55);
    doc.line(14, y, 196, y);
    y += 10;

    doc.setTextColor(100);
    doc.setFontSize(9);
    doc.text("This is a confirmed booking receipt generated by YatraPlanner.", 14, y);
    doc.text("For support, contact support@yatraplanner.in", 14, y + 6);

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("YatraPlanner — Making Indian Travel Simple", 14, 285);

    doc.save(`YatraPlanner_Receipt_${booking.booking_id}.pdf`);
  };

  if (!booking) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <p className="text-muted-foreground mb-4">No booking details found.</p>
          <Link to="/dashboard"><Button>Go to Dashboard</Button></Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-2xl">
        <Link to="/dashboard" className="inline-flex items-center gap-2 text-muted-foreground hover:text-primary mb-8 transition-colors">
          <ArrowLeft className="h-4 w-4" /> Back to Dashboard
        </Link>

        <div className="rounded-2xl bg-card border border-border overflow-hidden">
          {/* Green Header */}
          <div className="bg-primary p-8 text-center">
            <div className="flex items-center justify-center gap-2 mb-3">
              <MapPin className="h-7 w-7 text-primary-foreground" />
              <span className="font-display text-2xl font-bold text-primary-foreground">YatraPlanner</span>
            </div>
            <CheckCircle className="h-16 w-16 text-primary-foreground mx-auto mb-3" />
            <h1 className="text-2xl font-display font-bold text-primary-foreground">Booking Confirmed!</h1>
            <p className="text-primary-foreground/80 text-sm mt-1">Thank you for choosing YatraPlanner</p>
          </div>

          {/* Details */}
          <div className="p-8 space-y-5">
            <div className="flex items-center gap-3 p-4 rounded-xl bg-primary/5 border border-primary/10">
              <Ticket className="h-5 w-5 text-primary shrink-0" />
              <div>
                <p className="text-xs text-muted-foreground">Booking ID</p>
                <p className="font-mono font-bold text-primary">{booking.booking_id}</p>
              </div>
            </div>

            <div className="grid sm:grid-cols-2 gap-4">
              <div className="p-4 rounded-xl bg-muted">
                <p className="text-xs text-muted-foreground mb-1">
                  {booking.booking_type === "hotel" ? "Hotel" : "Transport"}
                </p>
                <p className="font-semibold">{booking.item_name}</p>
              </div>
              <div className="p-4 rounded-xl bg-muted">
                <p className="text-xs text-muted-foreground mb-1">Destination</p>
                <p className="font-semibold">{booking.destination}</p>
              </div>
              <div className="p-4 rounded-xl bg-muted flex items-center gap-2">
                <User className="h-4 w-4 text-muted-foreground" />
                <div>
                  <p className="text-xs text-muted-foreground">Guest</p>
                  <p className="font-semibold">{booking.guest_name}</p>
                </div>
              </div>
              <div className="p-4 rounded-xl bg-muted flex items-center gap-2">
                <Calendar className="h-4 w-4 text-muted-foreground" />
                <div>
                  <p className="text-xs text-muted-foreground">Date</p>
                  <p className="font-semibold">
                    {new Date(booking.booking_date).toLocaleDateString("en-IN", { dateStyle: "long" })}
                  </p>
                </div>
              </div>
            </div>

            <div className="p-4 rounded-xl bg-green-50 dark:bg-green-950/20 border border-green-200 dark:border-green-900 text-center">
              <p className="text-sm text-green-700 dark:text-green-400 font-medium">
                ✓ Status: Confirmed
              </p>
            </div>

            <div className="flex gap-3 pt-2">
              <Button onClick={exportReceipt} className="flex-1">
                <Download className="h-4 w-4 mr-2" /> Download Receipt
              </Button>
              <Link to="/dashboard/bookings" className="flex-1">
                <Button variant="outline" className="w-full">View All Bookings</Button>
              </Link>
            </div>
          </div>

          {/* Footer */}
          <div className="border-t border-border p-4 text-center">
            <p className="text-xs text-muted-foreground">
              YatraPlanner — Making Indian Travel Simple | support@yatraplanner.in
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BookingConfirmation;